// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.3
// source: proto/shenxian.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ShenxianService_ReportSystemState_FullMethodName = "/proto.ShenxianService/ReportSystemState"
	ShenxianService_ReportSystemInfo_FullMethodName  = "/proto.ShenxianService/ReportSystemInfo"
	ShenxianService_RequestTask_FullMethodName       = "/proto.ShenxianService/RequestTask"
	ShenxianService_IOStream_FullMethodName          = "/proto.ShenxianService/IOStream"
	ShenxianService_ReportGeoIP_FullMethodName       = "/proto.ShenxianService/ReportGeoIP"
	ShenxianService_ReportSystemInfo2_FullMethodName = "/proto.ShenxianService/ReportSystemInfo2"
)

// ShenxianServiceClient is the client API for ShenxianService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ShenxianServiceClient interface {
	ReportSystemState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[State, Receipt], error)
	ReportSystemInfo(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Receipt, error)
	RequestTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskResult, Task], error)
	IOStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IOStreamData, IOStreamData], error)
	ReportGeoIP(ctx context.Context, in *GeoIP, opts ...grpc.CallOption) (*GeoIP, error)
	ReportSystemInfo2(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Uint64Receipt, error)
}

type shenxianServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewShenxianServiceClient(cc grpc.ClientConnInterface) ShenxianServiceClient {
	return &shenxianServiceClient{cc}
}

func (c *shenxianServiceClient) ReportSystemState(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[State, Receipt], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShenxianService_ServiceDesc.Streams[0], ShenxianService_ReportSystemState_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[State, Receipt]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShenxianService_ReportSystemStateClient = grpc.BidiStreamingClient[State, Receipt]

func (c *shenxianServiceClient) ReportSystemInfo(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Receipt)
	err := c.cc.Invoke(ctx, ShenxianService_ReportSystemInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shenxianServiceClient) RequestTask(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[TaskResult, Task], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShenxianService_ServiceDesc.Streams[1], ShenxianService_RequestTask_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[TaskResult, Task]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShenxianService_RequestTaskClient = grpc.BidiStreamingClient[TaskResult, Task]

func (c *shenxianServiceClient) IOStream(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[IOStreamData, IOStreamData], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ShenxianService_ServiceDesc.Streams[2], ShenxianService_IOStream_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[IOStreamData, IOStreamData]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShenxianService_IOStreamClient = grpc.BidiStreamingClient[IOStreamData, IOStreamData]

func (c *shenxianServiceClient) ReportGeoIP(ctx context.Context, in *GeoIP, opts ...grpc.CallOption) (*GeoIP, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GeoIP)
	err := c.cc.Invoke(ctx, ShenxianService_ReportGeoIP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *shenxianServiceClient) ReportSystemInfo2(ctx context.Context, in *Host, opts ...grpc.CallOption) (*Uint64Receipt, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Uint64Receipt)
	err := c.cc.Invoke(ctx, ShenxianService_ReportSystemInfo2_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ShenxianServiceServer is the server API for ShenxianService service.
// All implementations should embed UnimplementedShenxianServiceServer
// for forward compatibility.
type ShenxianServiceServer interface {
	ReportSystemState(grpc.BidiStreamingServer[State, Receipt]) error
	ReportSystemInfo(context.Context, *Host) (*Receipt, error)
	RequestTask(grpc.BidiStreamingServer[TaskResult, Task]) error
	IOStream(grpc.BidiStreamingServer[IOStreamData, IOStreamData]) error
	ReportGeoIP(context.Context, *GeoIP) (*GeoIP, error)
	ReportSystemInfo2(context.Context, *Host) (*Uint64Receipt, error)
}

// UnimplementedShenxianServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedShenxianServiceServer struct{}

func (UnimplementedShenxianServiceServer) ReportSystemState(grpc.BidiStreamingServer[State, Receipt]) error {
	return status.Errorf(codes.Unimplemented, "method ReportSystemState not implemented")
}
func (UnimplementedShenxianServiceServer) ReportSystemInfo(context.Context, *Host) (*Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSystemInfo not implemented")
}
func (UnimplementedShenxianServiceServer) RequestTask(grpc.BidiStreamingServer[TaskResult, Task]) error {
	return status.Errorf(codes.Unimplemented, "method RequestTask not implemented")
}
func (UnimplementedShenxianServiceServer) IOStream(grpc.BidiStreamingServer[IOStreamData, IOStreamData]) error {
	return status.Errorf(codes.Unimplemented, "method IOStream not implemented")
}
func (UnimplementedShenxianServiceServer) ReportGeoIP(context.Context, *GeoIP) (*GeoIP, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportGeoIP not implemented")
}
func (UnimplementedShenxianServiceServer) ReportSystemInfo2(context.Context, *Host) (*Uint64Receipt, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReportSystemInfo2 not implemented")
}
func (UnimplementedShenxianServiceServer) testEmbeddedByValue() {}

// UnsafeShenxianServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ShenxianServiceServer will
// result in compilation errors.
type UnsafeShenxianServiceServer interface {
	mustEmbedUnimplementedShenxianServiceServer()
}

func RegisterShenxianServiceServer(s grpc.ServiceRegistrar, srv ShenxianServiceServer) {
	// If the following call panics, it indicates UnimplementedShenxianServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ShenxianService_ServiceDesc, srv)
}

func _ShenxianService_ReportSystemState_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShenxianServiceServer).ReportSystemState(&grpc.GenericServerStream[State, Receipt]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShenxianService_ReportSystemStateServer = grpc.BidiStreamingServer[State, Receipt]

func _ShenxianService_ReportSystemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenxianServiceServer).ReportSystemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShenxianService_ReportSystemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenxianServiceServer).ReportSystemInfo(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShenxianService_RequestTask_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShenxianServiceServer).RequestTask(&grpc.GenericServerStream[TaskResult, Task]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShenxianService_RequestTaskServer = grpc.BidiStreamingServer[TaskResult, Task]

func _ShenxianService_IOStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ShenxianServiceServer).IOStream(&grpc.GenericServerStream[IOStreamData, IOStreamData]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ShenxianService_IOStreamServer = grpc.BidiStreamingServer[IOStreamData, IOStreamData]

func _ShenxianService_ReportGeoIP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GeoIP)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenxianServiceServer).ReportGeoIP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShenxianService_ReportGeoIP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenxianServiceServer).ReportGeoIP(ctx, req.(*GeoIP))
	}
	return interceptor(ctx, in, info, handler)
}

func _ShenxianService_ReportSystemInfo2_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Host)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ShenxianServiceServer).ReportSystemInfo2(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ShenxianService_ReportSystemInfo2_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ShenxianServiceServer).ReportSystemInfo2(ctx, req.(*Host))
	}
	return interceptor(ctx, in, info, handler)
}

// ShenxianService_ServiceDesc is the grpc.ServiceDesc for ShenxianService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ShenxianService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "proto.ShenxianService",
	HandlerType: (*ShenxianServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ReportSystemInfo",
			Handler:    _ShenxianService_ReportSystemInfo_Handler,
		},
		{
			MethodName: "ReportGeoIP",
			Handler:    _ShenxianService_ReportGeoIP_Handler,
		},
		{
			MethodName: "ReportSystemInfo2",
			Handler:    _ShenxianService_ReportSystemInfo2_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReportSystemState",
			Handler:       _ShenxianService_ReportSystemState_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "RequestTask",
			Handler:       _ShenxianService_RequestTask_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "IOStream",
			Handler:       _ShenxianService_IOStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/shenxian.proto",
}
